Algoritmo "combinações"
// Lógica de Programação e Algorítimos
// Gustavo Guanabara 
// Descrição   : Realiza combinações de números
// Autor(a)    : Eduardo Chaves
// Data atual  : 7/20/2022
Var
combinacao1, combinacao2: inteiro

Inicio
para combinacao1 de 1 ate 3 faca
     para combinacao2 de 1 ate 3 faca
          escreval(combinacao1, combinacao2)
     fimpara
fimpara

Fimalgoritmo